version: '3'
services:
  octorpki:
    container_name: octorpki
    image: cloudflare/octorpki:latest
    ports:
      - '8080:8080'
    volumes:
      - octorpki-cache:/cache
      - octorpki-tals:/tals
    restart: always
  gortr:
    container_name: gortr
    image: cloudflare/gortr:latest
    ports:
      - '8282:8282'
      - '8283:8283'
    command: -cache http://octorpki:8080/output.json -verify=false -metrics.addr :8283
    depends_on:
      - octorpki
    restart: always
volumes:
  octorpki-cache:
  octorpki-tals:
